name: Devolv Action
description: Run Devolv DevOps Toolkit tools (drift, validate) in GitHub Actions

inputs:
  tool:
    description: Which Devolv tool to run (e.g. drift, validate)
    required: true
  policy-name:
    description: IAM policy name (required for drift)
    required: false
  path:
    description: Path to the local policy file or directory
    required: true
  fail-on-high-risk:
    description: Whether to fail the job if high-risk findings are detected (for validate)
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Devolv
      run: |
        pip install .[dev] --quiet --disable-pip-version-check > /dev/null 2>&1
      shell: bash

    - name: Run Devolv tool
      run: |
        if [ -z "${{ inputs.path }}" ]; then
          echo "::error::❌ Path input is required but was not provided."
          exit 1
        fi

        if [ "${{ inputs.tool }}" = "drift" ]; then
          if [ ! -f "${{ inputs.path }}" ]; then
            echo "::error::❌ Drift requires a file path. '${{ inputs.path }}' is not a file."
            exit 1
          fi
          devolv drift --policy-name "${{ inputs.policy-name }}" --file "${{ inputs.path }}"

        elif [ "${{ inputs.tool }}" = "validate" ]; then
          echo "::group::Running Devolv validate"
          devolv validate "${{ inputs.path }}"

          if [ "${{ inputs.fail-on-high-risk }}" = "true" ]; then
            # Check for high-risk findings and fail if present
            if devolv validate "${{ inputs.path }}" --json | grep -q '"level": "high"'; then
              echo "::error::❌ High-risk findings detected"
              exit 1
            fi
          fi
          echo "::endgroup::"

        else
          echo "::error::❌ Unknown tool: ${{ inputs.tool }}"
          exit 1
        fi
      shell: bash
