name: Devolv Action
description: Run Devolv DevOps Toolkit tools (drift, validate) in GitHub Actions

inputs:
  tool:
    description: Which Devolv tool to run (e.g. drift, validate)
    required: true
  policy-name:
    description: IAM policy name (required for drift)
    required: false
  path:
    description: Path to the local policy file or directory
    required: true
  fail-on-high-risk:
    description: Whether to fail the job if high-risk findings are detected (for validate)
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Devolv
      run: |
        pip install .[dev] --quiet --disable-pip-version-check
      shell: bash

    - name: Run Devolv tool
      run: |
        echo "::group::Running Devolv ${{ inputs.tool }}"

        if [ -z "${{ inputs.path }}" ]; then
          echo "::error::❌ Path input is required but was not provided."
          exit 1
        fi

        if [ "${{ inputs.tool }}" = "drift" ]; then
          if [ ! -f "${{ inputs.path }}" ]; then
            echo "::error::❌ Drift requires a file path. '${{ inputs.path }}' is not a file."
            exit 1
          fi
          devolv drift --policy-name "${{ inputs.policy-name }}" --file "${{ inputs.path }}"

        elif [ "${{ inputs.tool }}" = "validate" ]; then
          devolv validate "${{ inputs.path }}" --json > findings.json || true

          if grep -q '"level": "high"' findings.json; then
            echo "::error::❌ High-risk findings detected — see job summary"
            if [ "${{ inputs.fail-on-high-risk }}" = "true" ]; then
              exit 1
            fi
          else
            echo "✅ No high-risk findings"
          fi

        else
          echo "::error::❌ Unknown tool: ${{ inputs.tool }}"
          exit 1
        fi

        echo "::endgroup::"
      shell: bash
